"use client";

import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";

export default function Home() {
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true);
    const form = new FormData(event.currentTarget);
    const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) });
    setLoading(false); if (response.ok) { setSent(true); event.currentTarget.reset(); }
  }
  return <main className="min-h-screen overflow-hidden bg-[#0B274E] text-white">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><div className="font-serif text-3xl tracking-[-0.08em]">DEL SUR</div><a href="#consulta" className="hidden rounded-full border border-[#EBC05A]/50 px-5 py-2 text-sm font-semibold text-[#FFDB5A] transition hover:bg-[#EBC05A] hover:text-[#0B274E] sm:block">Hablar con un asesor</a></nav>
    <section className="relative mx-auto grid max-w-7xl gap-16 px-6 pb-24 pt-16 lg:grid-cols-[1.2fr_.8fr] lg:px-10 lg:pb-32 lg:pt-24"><div className="pointer-events-none absolute -right-24 top-4 h-80 w-80 rounded-full bg-[#EBC05A]/10 blur-3xl" /><div className="relative"><p className="mb-6 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.32em] text-[#EBC05A]">✦ Financiera del Sur</p><h1 className="max-w-3xl font-serif text-6xl leading-[.9] tracking-[-0.06em] sm:text-8xl">El impulso que tu próximo paso necesita.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/70">Encontrá opciones de financiación claras para concretar eso que venís planeando. Nuestro equipo te acompaña de principio a fin.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#consulta"><Button size="lg" className="rounded-full bg-[#EBC05A] px-7 text-[#0B274E] hover:bg-[#FFDB5A]">Quiero que me contacten ↗</Button></a><a href="#beneficios" className="rounded-full border border-white/20 px-6 py-3 text-sm font-semibold text-white/80 transition hover:border-[#EBC05A] hover:text-[#FFDB5A]">Conocé más</a></div></div><div className="relative flex items-end justify-end"><div className="w-full max-w-sm rounded-[2rem] border border-white/10 bg-white/[.06] p-8 backdrop-blur"><p className="text-sm text-white/50">Una decisión importante merece</p><p className="mt-3 font-serif text-4xl leading-none text-[#FFDB5A]">acompañamiento real.</p><div className="mt-12 grid grid-cols-2 gap-4 border-t border-white/10 pt-5 text-xs text-white/60"><span>Atención personalizada</span><span>Respuesta ágil</span></div></div></div></section>
    <section id="beneficios" className="bg-[#F8F5EE] px-6 py-20 text-[#0B274E] lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#8B702F]">Por qué Del Sur</p><div className="mt-8 grid gap-6 md:grid-cols-3"><article className="border-t-2 border-[#EBC05A] pt-5"><h2 className="font-serif text-3xl">Claridad</h2><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Te explicamos cada alternativa de forma simple y transparente.</p></article><article className="border-t-2 border-[#EBC05A] pt-5"><h2 className="font-serif text-3xl">Cercanía</h2><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Una persona real responde tus preguntas y acompaña tu proceso.</p></article><article className="border-t-2 border-[#EBC05A] pt-5"><h2 className="font-serif text-3xl">Agilidad</h2><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Recibí una primera orientación sin vueltas ni formularios interminables.</p></article></div></div></section>
    <section id="consulta" className="bg-[#0B274E] px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#EBC05A]">Empecemos</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-none tracking-[-.04em]">Contanos qué estás buscando.</h2><p className="mt-6 max-w-sm leading-7 text-white/60">Dejanos tus datos y un asesor se va a comunicar con vos.</p></div><div className="rounded-[2rem] bg-[#F8F5EE] p-6 text-[#0B274E] sm:p-10">{sent ? <div className="flex min-h-72 flex-col items-center justify-center text-center"><span className="text-4xl text-[#8B702F]">✓</span><h3 className="mt-5 font-serif text-3xl">¡Recibimos tu consulta!</h3><p className="mt-3 max-w-sm text-sm text-[#0B274E]/60">Un asesor de Del Sur se pondrá en contacto con vos.</p></div> : <form onSubmit={submit} className="grid gap-5"><input name="name" required placeholder="Nombre y apellido" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="email" required type="email" placeholder="Email" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="phone" required placeholder="Teléfono / WhatsApp" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><textarea name="message" placeholder="¿En qué podemos ayudarte?" rows={3} className="resize-none border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="website" tabIndex={-1} autoComplete="off" className="hidden" /><Button disabled={loading} size="lg" className="mt-3 rounded-full bg-[#0B274E] text-white hover:bg-[#143964]">{loading ? "Enviando…" : "Solicitar asesoramiento"} ↗</Button><p className="text-xs text-[#0B274E]/45">Al enviar aceptás que podamos contactarte por los datos proporcionados.</p></form>}</div></div></section>
    <footer className="flex flex-col gap-2 border-t border-white/10 bg-[#0B274E] px-6 py-8 text-xs text-white/45 sm:flex-row sm:justify-between lg:px-10"><span>DEL SUR · FINANCIERA</span><span>San Miguel de Tucumán · Argentina</span></footer>
  </main>;
}
