"use client";

import Image from "next/image";
import { FormEvent, useRef, useState } from "react";
import { motion, useScroll, useTransform, type Variants } from "framer-motion";
import { Button } from "@/components/ui/button";

const reveal: Variants = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.65, ease: "easeOut" } } };
const stagger: Variants = { hidden: {}, visible: { transition: { staggerChildren: 0.12 } } };

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  return <motion.div className={className} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: false, amount: 0.22 }} transition={{ delay }}>{children}</motion.div>;
}

export default function Home() {
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const heroRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const logoY = useTransform(scrollYProgress, [0, 1], [0, 80]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true);
    const form = new FormData(event.currentTarget);
    const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) });
    setLoading(false); if (response.ok) { setSent(true); event.currentTarget.reset(); }
  }
  return <main className="min-h-screen overflow-hidden bg-[#0B274E] text-white">
    <motion.nav initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#0B274E]/75 px-6 py-4 backdrop-blur-xl lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="#inicio" aria-label="Del Sur inicio"><Image src="/brand/logo-del-sur.png" alt="Del Sur Financiera" width={154} height={82} className="h-14 w-auto object-contain" priority /></a><div className="flex items-center gap-3"><a href="#consulta" className="hidden rounded-full border border-[#EBC05A]/45 px-5 py-2 text-sm font-semibold text-[#FFDB5A] transition hover:bg-[#EBC05A] hover:text-[#0B274E] sm:block">Hablar con un asesor</a><motion.a whileHover={{ y: -2 }} whileTap={{ scale: .97 }} href="/admin" className="rounded-full bg-[#EBC05A] px-4 py-2 text-sm font-bold text-[#0B274E] transition hover:bg-[#FFDB5A]">Iniciar sesión</motion.a></div></div></motion.nav>
    <section id="inicio" ref={heroRef} className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-14 px-6 pb-24 pt-36 lg:grid-cols-[1.1fr_.9fr] lg:px-10"><div className="pointer-events-none absolute -right-24 top-20 h-96 w-96 rounded-full bg-[#EBC05A]/10 blur-3xl" /><motion.div variants={stagger} initial="hidden" animate="visible" className="relative"><motion.p variants={reveal} className="mb-6 text-xs font-bold uppercase tracking-[0.32em] text-[#EBC05A]">✦ Una decisión importante merece acompañamiento real</motion.p><motion.h1 variants={reveal} className="max-w-3xl font-serif text-6xl leading-[.9] tracking-[-.06em] sm:text-8xl">El impulso que tu próximo paso necesita.</motion.h1><motion.p variants={reveal} className="mt-8 max-w-xl text-lg leading-8 text-white/70">Encontrá opciones de financiación claras para concretar eso que venís planeando. Nuestro equipo te acompaña de principio a fin.</motion.p><motion.div variants={reveal} className="mt-10 flex flex-wrap gap-4"><motion.a whileHover={{ y: -3 }} whileTap={{ scale: .98 }} href="#consulta"><Button size="lg" className="rounded-full bg-[#EBC05A] px-7 text-[#0B274E] shadow-[0_16px_40px_rgba(235,192,90,.18)] hover:bg-[#FFDB5A]">Quiero que me contacten ↗</Button></motion.a><motion.a whileHover={{ y: -3 }} href="#beneficios" className="rounded-full border border-white/20 px-6 py-3 text-sm font-semibold text-white/80 transition hover:border-[#EBC05A] hover:text-[#FFDB5A]">Conocé más</motion.a></motion.div></motion.div><motion.div style={{ y: logoY }} initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .9, delay: .2, ease: "easeOut" }} className="relative flex items-center justify-center"><div className="absolute h-72 w-72 rounded-full border border-[#EBC05A]/20" /><div className="absolute h-96 w-96 rounded-full border border-white/5" /><Image src="/brand/logo-del-sur.png" alt="Del Sur Financiera" width={700} height={375} className="relative w-full max-w-xl object-contain drop-shadow-[0_20px_60px_rgba(0,0,0,.28)]" /></motion.div></section>
    <section id="beneficios" className="bg-[#F8F5EE] px-6 py-24 text-[#0B274E] lg:px-10"><div className="mx-auto max-w-7xl"><Reveal><p className="text-xs font-bold uppercase tracking-[.3em] text-[#8B702F]">Por qué Del Sur</p><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-none tracking-[-.04em] sm:text-6xl">Financiación con una mirada más humana.</h2></Reveal><motion.div variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: false, amount: .2 }} className="mt-14 grid gap-8 md:grid-cols-3"><motion.article variants={reveal} className="border-t-2 border-[#EBC05A] pt-6"><span className="font-serif text-5xl text-[#D8CC88]">01</span><h3 className="mt-5 font-serif text-3xl">Claridad</h3><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Te explicamos cada alternativa de forma simple y transparente.</p></motion.article><motion.article variants={reveal} className="border-t-2 border-[#EBC05A] pt-6"><span className="font-serif text-5xl text-[#D8CC88]">02</span><h3 className="mt-5 font-serif text-3xl">Cercanía</h3><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Una persona real responde tus preguntas y acompaña tu proceso.</p></motion.article><motion.article variants={reveal} className="border-t-2 border-[#EBC05A] pt-6"><span className="font-serif text-5xl text-[#D8CC88]">03</span><h3 className="mt-5 font-serif text-3xl">Agilidad</h3><p className="mt-3 text-sm leading-6 text-[#0B274E]/65">Recibí una primera orientación sin vueltas ni formularios interminables.</p></motion.article></motion.div></div></section>
    <section id="consulta" className="bg-[#0B274E] px-6 py-24 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal className="self-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#EBC05A]">Empecemos</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-none tracking-[-.04em]">Contanos qué estás buscando.</h2><p className="mt-6 max-w-sm leading-7 text-white/60">Dejanos tus datos y un asesor se va a comunicar con vos.</p></Reveal><Reveal delay={.1}><div className="rounded-[2rem] bg-[#F8F5EE] p-6 text-[#0B274E] shadow-2xl sm:p-10">{sent ? <div className="flex min-h-72 flex-col items-center justify-center text-center"><motion.span initial={{ scale: 0 }} animate={{ scale: 1 }} className="text-5xl text-[#8B702F]">✓</motion.span><h3 className="mt-5 font-serif text-3xl">¡Recibimos tu consulta!</h3><p className="mt-3 max-w-sm text-sm text-[#0B274E]/60">Un asesor de Del Sur se pondrá en contacto con vos.</p></div> : <form onSubmit={submit} className="grid gap-5"><input name="name" required placeholder="Nombre y apellido" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="email" required type="email" placeholder="Email" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="phone" required placeholder="Teléfono / WhatsApp" className="border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><textarea name="message" placeholder="¿En qué podemos ayudarte?" rows={3} className="resize-none border-b border-[#0B274E]/20 bg-transparent px-1 py-3 outline-none placeholder:text-[#0B274E]/40 focus:border-[#8B702F]" /><input name="website" tabIndex={-1} autoComplete="off" className="hidden" /><motion.div whileHover={{ y: -2 }} whileTap={{ scale: .98 }}><Button disabled={loading} size="lg" className="mt-3 w-full rounded-full bg-[#0B274E] text-white hover:bg-[#143964]">{loading ? "Enviando…" : "Solicitar asesoramiento"} ↗</Button></motion.div><p className="text-xs text-[#0B274E]/45">Al enviar aceptás que podamos contactarte por los datos proporcionados.</p></form>}</div></Reveal></div></section>
    <footer className="flex flex-col gap-2 border-t border-white/10 bg-[#0B274E] px-6 py-8 text-xs text-white/45 sm:flex-row sm:justify-between lg:px-10"><span>DEL SUR · FINANCIERA</span><a href="/admin" className="transition hover:text-[#FFDB5A]">Acceso administrativo</a><span>San Miguel de Tucumán · Argentina</span></footer>
  </main>;
}
